### ISSUE TITLE
errors for annotations when using the ArtifactHub chart

### ISSUE THREAD

**Issue by ilyatovbin-pp** [featurehub-io/featurehub-helm#5]
`helm template featurehub -f values.yaml .`
getting the following error after adding annotations for the global ingress:
```
coalesce.go:203: warning: destination for annotations is a table. Ignoring non-table value []
coalesce.go:200: warning: cannot overwrite table with non table for annotations (map[alb.ingress.kubernetes.io/backend-protocol:HTTP alb.ingress.kubernetes.io/certificate-arn:redacted alb.ingress.kubernetes.io/group.name:testing-featurehub alb.ingress.kubernetes.io/listen-ports:[{"HTTPS":443}] alb.ingress.kubernetes.io/load-balancer-attributes:routing.http.drop_invalid_header_fields.enabled=true alb.ingress.kubernetes.io/scheme:internal alb.ingress.kubernetes.io/ssl-policy:ELBSecurityPolicy-FS-1-2-Res-2020-10 alb.ingress.kubernetes.io/tags:environment=testing,product=featurehub,sub-product=ALB-internal alb.ingress.kubernetes.io/target-type:ip kubernetes.io/ingress.class:alb])
coalesce.go:200: warning: cannot overwrite table with non table for annotations (map[alb.ingress.kubernetes.io/backend-protocol:HTTP alb.ingress.kubernetes.io/certificate-arn:redacted alb.ingress.kubernetes.io/group.name:testing-featurehub alb.ingress.kubernetes.io/listen-ports:[{"HTTPS":443}] alb.ingress.kubernetes.io/load-balancer-attributes:routing.http.drop_invalid_header_fields.enabled=true alb.ingress.kubernetes.io/scheme:internal alb.ingress.kubernetes.io/ssl-policy:ELBSecurityPolicy-FS-1-2-Res-2020-10 alb.ingress.kubernetes.io/tags:environment=testing,product=featurehub,sub-product=ALB-internal alb.ingress.kubernetes.io/target-type:ip kubernetes.io/ingress.class:alb])
coalesce.go:200: warning: cannot overwrite table with non table for annotations (map[alb.ingress.kubernetes.io/backend-protocol:HTTP alb.ingress.kubernetes.io/certificate-arn:redacted alb.ingress.kubernetes.io/group.name:testing-featurehub alb.ingress.kubernetes.io/listen-ports:[{"HTTPS":443}] alb.ingress.kubernetes.io/load-balancer-attributes:routing.http.drop_invalid_header_fields.enabled=true alb.ingress.kubernetes.io/scheme:internal alb.ingress.kubernetes.io/ssl-policy:ELBSecurityPolicy-FS-1-2-Res-2020-10 alb.ingress.kubernetes.io/tags:environment=testing,product=featurehub,sub-product=ALB-internal alb.ingress.kubernetes.io/target-type:ip kubernetes.io/ingress.class:alb])
coalesce.go:203: warning: destination for annotations is a table. Ignoring non-table value []
coalesce.go:203: warning: destination for annotations is a table. Ignoring non-table value []
coalesce.go:203: warning: destination for annotations is a table. Ignoring non-table value []
coalesce.go:203: warning: destination for annotations is a table. Ignoring non-table value []
coalesce.go:203: warning: destination for annotations is a table. Ignoring non-table value []
```
cloned this repo and used this chart as the source with the same values.yaml and everything seems to be fine.
looks like both of them are 3.0.6 and the global-ingress.yaml is the same (unless im missing something) so, weird.  
might want to look into it.

Chart.yaml
```yaml
apiVersion: v2
description: FeatureHub on EKS
name: featurehub
version: 1.0.0

dependencies:
- name: featurehub
  version: ~3.0.0
  repository: https://featurehub-io.github.io/featurehub-helm/

```

values.yaml:
```yaml
featurehub:
  global:
    ingress:
      annotations:
        alb.ingress.kubernetes.io/certificate-arn: redacted
        alb.ingress.kubernetes.io/group.name: testing-featurehub
        alb.ingress.kubernetes.io/tags: environment=testing,product=featurehub,sub-product=ALB-internal
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internal
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/backend-protocol: HTTP
        alb.ingress.kubernetes.io/load-balancer-attributes: routing.http.drop_invalid_header_fields.enabled=true
        alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-FS-1-2-Res-2020-10"
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
```
